/**
 * Harvest Schema - Goal-based relationship nurturing algorithms
 * 
 * The Harvest module proactively suggests relationship maintenance
 * based on user-selected algorithms (goals) that align with their values.
 */

import { co, z } from "jazz-tools";

/**
 * Algorithm Types - Different approaches to relationship maintenance
 * 
 * Based on psychological frameworks and relationship research:
 * - Tend & Befriend: Focus on emotional support and deepening bonds (Taylor, 2006)
 * - Plant & Prune: Strategic allocation of social energy (Dunbar, 1998)
 * - Cultivate: Consistent maintenance and growth (Reis & Shaver, 1988)
 */
export type AlgorithmType = 
  | "TEND_AND_BEFRIEND"    // Nurture existing close relationships
  | "PLANT_AND_PRUNE"      // Strategic pruning + planting new connections
  | "CULTIVATE"            // Consistent maintenance across all layers
  | "INNER_CIRCLE"         // Focus intensely on intimate core
  | "EXPAND_HORIZONS"      // Meet new people, expand social circle
  | "REKINDLE"             // Reconnect with past relationships
  | "BALANCE";             // Maintain equilibrium across all layers

/**
 * Algorithm configurations with research-backed parameters
 */
export interface AlgorithmConfig {
  type: AlgorithmType;
  name: string;
  description: string;
  targetLayers: number[];        // Which Dunbar layers to focus on
  checkFrequency: number;        // Days between checks
  actionThreshold: number;       // Days since last contact before suggesting action
  priorityWeights: {             // How to prioritize suggestions
    recency: number;             // Weight for time since last contact
    frequency: number;           // Weight for usual contact frequency
    quality: number;             // Weight for interaction quality
    familyBonus: number;         // Extra weight for family
  };
}

/**
 * User's active algorithms
 * Users can have multiple algorithms running simultaneously
 */
export const HarvestAlgorithm = co.map({
  type: z.string(),
  enabled: z.boolean(),
  createdAt: z.string(),
  lastRunAt: z.string().optional(),
  customSettings: z.string().optional(), // JSON string of Partial<AlgorithmConfig>
});

/**
 * Suggested actions generated by algorithms
 */
export const HarvestSuggestion = co.map({
  contactId: z.string(),               // Reference to Contact
  algorithmType: z.string(),           // Which algorithm generated this
  actionType: z.string(),              // "CALL" | "TEXT" | "MEET" | "CHECK_IN"
  priority: z.number(),                // 0-100, higher = more urgent
  reason: z.string(),                  // Human-readable explanation
  generatedAt: z.string(),             // ISO timestamp
  dismissedAt: z.string().optional(),  // User can dismiss suggestions
  completedAt: z.string().optional(),  // Marked complete when action taken
  snoozedUntil: z.string().optional(), // Temporarily hide suggestion
});

/**
 * Notification schedule for push reminders
 */
export const HarvestNotificationSettings = co.map({
  enabled: z.boolean(),
  frequency: z.string(),                    // "DAILY" | "WEEKLY" | "BIWEEKLY"
  preferredTime: z.string(),                // "08:00" format
  preferredDays: z.array(z.string()),       // ["MON", "WED", "FRI"]
  quietHoursStart: z.string().optional(),   // "22:00"
  quietHoursEnd: z.string().optional(),     // "08:00"
});

/**
 * Volition Types - Different categories of relationship cultivation strategies
 */
export type VolitionType = 
  | "RANKING"       // Builds intuitiveRank data
  | "MAINTENANCE"   // Relationship actions
  | "QUALITY"       // Data enrichment
  | "DISCOVERY";    // Feature exploration

/**
 * Volition - User-selected relationship cultivation strategies
 * Volitions are active goals that generate daily actions and track time investment
 */
export const Volition = co.map({
  id: z.string(),
  type: z.string(),  // VolitionType
  
  // Metadata
  name: z.string(),
  description: z.string(),
  emoji: z.string(),
  
  // Configuration
  isActive: z.boolean(),
  startedAt: z.string().optional(),
  completedAt: z.string().optional(),
  pausedAt: z.string().optional(),
  
  // Progress Tracking
  dailyTarget: z.number(),           // How many tasks per day
  totalTarget: z.number().optional(), // Total goal (if applicable)
  currentProgress: z.number(),
  
  // Streak
  streakCount: z.number(),
  longestStreak: z.number(),
  lastCompletedDate: z.string().optional(),
  
  // Rewards
  badgeId: z.string().optional(),
  rewardDescription: z.string().optional(),
  
  // Feature Flag Configuration
  enableDailyModal: z.boolean(),
  modalType: z.string().optional(),           // "RANKING" | "CONTACT" | "RATE"
  targetLayer: z.number().optional(),         // For layer-specific volitions
  contactFilter: z.string().optional(),       // "LAPSED" | "FREQUENT" | "ALL"
  
  // Time Tracking
  estimatedMinutesPerWeek: z.number(),        // Estimated weekly time investment
});

/**
 * Badge Categories
 */
export type BadgeCategory = 
  | "COMPLETION"    // Milestone achievements
  | "STREAK"        // Consistency
  | "ACTION"        // Relationship actions
  | "QUALITY";      // Data quality

/**
 * Badge - Achievements earned through volition completion
 */
export const Badge = co.map({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  emoji: z.string(),
  
  // Category
  category: z.string(), // BadgeCategory
  
  // Requirements
  requirementType: z.string(),        // "COUNT" | "STREAK" | "COMPLETE_ALL"
  requirementTarget: z.number().optional(),
  volitionId: z.string().optional(),  // Which volition unlocks this
  
  // Status
  isUnlocked: z.boolean(),
  unlockedAt: z.string().optional(),
  progress: z.number().optional(),    // For locked badges
  
  // Rewards
  unlocks: z.array(z.string()).optional(), // Feature IDs this unlocks
});

/**
 * User's Harvest profile - all quest and badge data
 */
export const HarvestProfile = co.map({
  // Legacy fields (keep for backward compatibility)
  lastGeneratedAt: z.string().optional(),
  totalActionsCompleted: z.number(),
  currentStreak: z.number(),
  longestStreak: z.number(),
  notificationEnabled: z.boolean(),
  notificationFrequency: z.string(),
  notificationTime: z.string(),
  
  // Volition System fields
  totalVolitionsCompleted: z.number(),
  totalBadgesEarned: z.number(),
  lastDailyCompletionDate: z.string().optional(),
  todayActionsCompleted: z.number(),
  todayActionsTotal: z.number(),
  
  // Settings
  preferredReminderTime: z.string(),  // "08:00"
  quietHoursStart: z.string().optional(),
  quietHoursEnd: z.string().optional(),
});

// Store data as lists on the root
export const HarvestAlgorithmList = co.list(HarvestAlgorithm);
export const HarvestSuggestionList = co.list(HarvestSuggestion);
export const VolitionList = co.list(Volition);
export const BadgeList = co.list(Badge);

/**
 * Algorithm Presets - Pre-configured for different relationship goals
 */
export const ALGORITHM_PRESETS: Record<AlgorithmType, AlgorithmConfig> = {
  TEND_AND_BEFRIEND: {
    type: "TEND_AND_BEFRIEND",
    name: "Tend & Befriend",
    description: "Nurture your closest relationships with regular check-ins and emotional support. Focuses on layers 0-2.",
    targetLayers: [0, 1, 2],
    checkFrequency: 1, // Daily
    actionThreshold: 7, // Suggest if no contact in 7 days
    priorityWeights: {
      recency: 0.5,
      frequency: 0.2,
      quality: 0.2,
      familyBonus: 0.1,
    },
  },
  PLANT_AND_PRUNE: {
    type: "PLANT_AND_PRUNE",
    name: "Plant & Prune",
    description: "Strategic social energy allocation. Prune weak connections, invest in promising ones. Focuses on layers 2-4.",
    targetLayers: [2, 3, 4],
    checkFrequency: 7, // Weekly
    actionThreshold: 30, // Suggest if no contact in 30 days
    priorityWeights: {
      recency: 0.3,
      frequency: 0.4, // Prioritize people you usually talk to often
      quality: 0.2,
      familyBonus: 0.1,
    },
  },
  CULTIVATE: {
    type: "CULTIVATE",
    name: "Cultivate",
    description: "Consistent maintenance across all relationship layers. Balanced approach to keep your garden healthy.",
    targetLayers: [0, 1, 2, 3, 4],
    checkFrequency: 3, // Every 3 days
    actionThreshold: 14, // Suggest if no contact in 14 days
    priorityWeights: {
      recency: 0.3,
      frequency: 0.3,
      quality: 0.3,
      familyBonus: 0.1,
    },
  },
  INNER_CIRCLE: {
    type: "INNER_CIRCLE",
    name: "Inner Circle",
    description: "Intensely focus on your intimate core and sympathy group. Deep over wide.",
    targetLayers: [0, 1],
    checkFrequency: 1, // Daily
    actionThreshold: 3, // Very short threshold
    priorityWeights: {
      recency: 0.6, // Heavy weight on recency
      frequency: 0.1,
      quality: 0.2,
      familyBonus: 0.1,
    },
  },
  EXPAND_HORIZONS: {
    type: "EXPAND_HORIZONS",
    name: "Expand Horizons",
    description: "Focus on meeting new people and moving acquaintances to closer layers.",
    targetLayers: [3, 4, 5],
    checkFrequency: 7, // Weekly
    actionThreshold: 60, // Long threshold - focus on people you rarely see
    priorityWeights: {
      recency: 0.2,
      frequency: 0.2,
      quality: 0.4, // Prioritize quality interactions
      familyBonus: 0.2,
    },
  },
  REKINDLE: {
    type: "REKINDLE",
    name: "Rekindle",
    description: "Reconnect with people you've drifted from. Revive old friendships.",
    targetLayers: [2, 3, 4, 5],
    checkFrequency: 14, // Biweekly
    actionThreshold: 90, // Suggest people you haven't talked to in 3+ months
    priorityWeights: {
      recency: 0.7, // Heavy focus on people you haven't talked to
      frequency: 0.1,
      quality: 0.1,
      familyBonus: 0.1,
    },
  },
  BALANCE: {
    type: "BALANCE",
    name: "Balance",
    description: "Maintain equilibrium across all layers. No one gets neglected.",
    targetLayers: [0, 1, 2, 3, 4],
    checkFrequency: 5, // Every 5 days
    actionThreshold: 21, // 3 weeks
    priorityWeights: {
      recency: 0.25,
      frequency: 0.25,
      quality: 0.25,
      familyBonus: 0.25,
    },
  },
};

/**
 * Action type definitions
 */
export const ACTION_TYPES = {
  CALL: {
    name: "Call",
    icon: "📞",
    description: "Have a voice conversation",
    typicalDuration: 15, // minutes
  },
  TEXT: {
    name: "Text",
    icon: "💬",
    description: "Send a message",
    typicalDuration: 5,
  },
  MEET: {
    name: "Meet",
    icon: "🤝",
    description: "Meet in person",
    typicalDuration: 60,
  },
  CHECK_IN: {
    name: "Check In",
    icon: "👋",
    description: "Quick hello or status check",
    typicalDuration: 2,
  },
  VIDEO_CALL: {
    name: "Video Call",
    icon: "📹",
    description: "Video chat",
    typicalDuration: 30,
  },
} as const;

/**
 * Volition Presets - Pre-configured relationship cultivation strategies
 */
export interface VolitionConfig {
  id: string;
  type: VolitionType;
  name: string;
  description: string;
  emoji: string;
  dailyTarget: number;
  totalTarget?: number;
  badgeId?: string;
  rewardDescription?: string;
  enableDailyModal: boolean;
  modalType?: "RANKING" | "CONTACT" | "RATE";
  targetLayer?: number;
  contactFilter?: "LAPSED" | "FREQUENT" | "ALL";
  estimatedMinutesPerWeek: number;  // Weekly time investment estimate
}

export const VOLITION_PRESETS: Record<string, VolitionConfig> = {
  KNOW_YOUR_CIRCLE: {
    id: "KNOW_YOUR_CIRCLE",
    type: "RANKING",
    name: "Know Your Circle",
    description: "Answer 2-3 comparison questions daily to understand your true priorities",
    emoji: "🎯",
    dailyTarget: 2,
    totalTarget: 100,
    badgeId: "CIRCLE_CLARITY",
    rewardDescription: "Unlock Circle Clarity badge + advanced reports",
    enableDailyModal: true,
    modalType: "RANKING",
    estimatedMinutesPerWeek: 5, // 2 questions/day × 20 sec × 7 days ≈ 5 min
  },
  
  COMPLETE_TRIBE_RANKING: {
    id: "COMPLETE_TRIBE_RANKING",
    type: "RANKING",
    name: "Complete Your Tribe",
    description: "Rank all contacts in your Tribe layer",
    emoji: "👥",
    dailyTarget: 5,
    badgeId: "TRIBE_RANKER",
    rewardDescription: "Unlock Tribe Ranker badge + layer insights",
    enableDailyModal: true,
    modalType: "RANKING",
    targetLayer: 2,
    estimatedMinutesPerWeek: 12, // 5 questions/day × 20 sec × 7 days ≈ 12 min
  },
  
  WEEKLY_CHECKIN: {
    id: "WEEKLY_CHECKIN",
    type: "MAINTENANCE",
    name: "Weekly Check-In Streak",
    description: "Reach out to someone every week for 4 weeks",
    emoji: "💬",
    dailyTarget: 1,
    totalTarget: 28,
    badgeId: "STEADY_GARDENER",
    rewardDescription: "Unlock Steady Gardener badge",
    enableDailyModal: true,
    modalType: "CONTACT",
    contactFilter: "FREQUENT",
    estimatedMinutesPerWeek: 60, // ~15 min per contact × 4 contacts/week
  },
  
  REKINDLE_CONNECTIONS: {
    id: "REKINDLE_CONNECTIONS",
    type: "MAINTENANCE",
    name: "Rekindle Old Connections",
    description: "Reconnect with 5 people you haven't talked to in 90+ days",
    emoji: "🔥",
    dailyTarget: 1,
    totalTarget: 5,
    badgeId: "REKINDLER",
    rewardDescription: "Unlock Rekindler badge",
    enableDailyModal: true,
    modalType: "CONTACT",
    contactFilter: "LAPSED",
    estimatedMinutesPerWeek: 90, // ~20 min per rekindled contact (more thoughtful)
  },
  
  RATE_INTERACTIONS: {
    id: "RATE_INTERACTIONS",
    type: "QUALITY",
    name: "Rate Your Interactions",
    description: "Add quality ratings to your last 20 interactions",
    emoji: "⭐",
    dailyTarget: 2,
    totalTarget: 20,
    badgeId: "REFLECTIVE",
    rewardDescription: "Unlock Reflective badge + better personalization",
    enableDailyModal: true,
    modalType: "RATE",
    estimatedMinutesPerWeek: 10, // 2 ratings/day × 30 sec × 7 days ≈ 7 min
  },
  
  EXPLORE_GARDEN: {
    id: "EXPLORE_GARDEN",
    type: "DISCOVERY",
    name: "Explore Your Garden",
    description: "Learn about each Dunbar layer",
    emoji: "🌱",
    dailyTarget: 1,
    totalTarget: 6,
    badgeId: "GARDENER",
    rewardDescription: "Unlock Gardener badge",
    enableDailyModal: false,
    estimatedMinutesPerWeek: 15, // ~15 min reviewing layers/features
  },
};

/**
 * Badge Definitions
 */
export interface BadgeConfig {
  id: string;
  name: string;
  description: string;
  emoji: string;
  category: BadgeCategory;
  requirementType: "COUNT" | "STREAK" | "COMPLETE_ALL";
  requirementTarget?: number;
  volitionId?: string;
  unlocks?: string[];
}

export const BADGE_DEFINITIONS: Record<string, BadgeConfig> = {
  // Completion Badges
  CIRCLE_CLARITY: {
    id: "CIRCLE_CLARITY",
    name: "Circle Clarity",
    description: "You know where you stand with people",
    emoji: "🎯",
    category: "COMPLETION",
    requirementType: "COUNT",
    requirementTarget: 100,
    volitionId: "KNOW_YOUR_CIRCLE",
    unlocks: ["RANKING_REPORT"],
  },
  
  TRIBE_RANKER: {
    id: "TRIBE_RANKER",
    name: "Tribe Ranker",
    description: "Master of your Tribe relationships",
    emoji: "👥",
    category: "COMPLETION",
    requirementType: "COMPLETE_ALL",
    volitionId: "COMPLETE_TRIBE_RANKING",
    unlocks: ["TRIBE_INSIGHTS"],
  },
  
  FULL_GARDEN_RANKER: {
    id: "FULL_GARDEN_RANKER",
    name: "Full Garden Ranker",
    description: "You've ranked every relationship in your life",
    emoji: "🏆",
    category: "COMPLETION",
    requirementType: "COMPLETE_ALL",
    unlocks: ["MASTER_THEME", "ADVANCED_ANALYTICS"],
  },
  
  // Streak Badges
  WEEK_WARRIOR: {
    id: "WEEK_WARRIOR",
    name: "Week Warrior",
    description: "Maintained volitions 7 days in a row",
    emoji: "🔥",
    category: "STREAK",
    requirementType: "STREAK",
    requirementTarget: 7,
  },
  
  MONTH_MASTER: {
    id: "MONTH_MASTER",
    name: "Month Master",
    description: "Maintained volitions 30 days in a row",
    emoji: "💎",
    category: "STREAK",
    requirementType: "STREAK",
    requirementTarget: 30,
  },
  
  YEAR_GARDENER: {
    id: "YEAR_GARDENER",
    name: "Year Gardener",
    description: "A full year of relationship cultivation",
    emoji: "🌳",
    category: "STREAK",
    requirementType: "STREAK",
    requirementTarget: 365,
  },
  
  // Action Badges
  STEADY_GARDENER: {
    id: "STEADY_GARDENER",
    name: "Steady Gardener",
    description: "Consistent relationship maintenance",
    emoji: "🌿",
    category: "ACTION",
    requirementType: "COUNT",
    requirementTarget: 28,
    volitionId: "WEEKLY_CHECKIN",
  },
  
  REKINDLER: {
    id: "REKINDLER",
    name: "Rekindler",
    description: "You brought old friendships back to life",
    emoji: "✨",
    category: "ACTION",
    requirementType: "COUNT",
    requirementTarget: 5,
    volitionId: "REKINDLE_CONNECTIONS",
  },
  
  SOCIAL_BUTTERFLY: {
    id: "SOCIAL_BUTTERFLY",
    name: "Social Butterfly",
    description: "You've nurtured connections across your entire garden",
    emoji: "🦋",
    category: "ACTION",
    requirementType: "COUNT",
    requirementTarget: 100,
  },
  
  // Quality Badges
  REFLECTIVE: {
    id: "REFLECTIVE",
    name: "Reflective",
    description: "You think deeply about your relationships",
    emoji: "💭",
    category: "QUALITY",
    requirementType: "COUNT",
    requirementTarget: 20,
    volitionId: "RATE_INTERACTIONS",
    unlocks: ["QUALITY_INSIGHTS"],
  },
  
  GARDENER: {
    id: "GARDENER",
    name: "Gardener",
    description: "You understand all layers of your social garden",
    emoji: "🌱",
    category: "QUALITY",
    requirementType: "COUNT",
    requirementTarget: 6,
    volitionId: "EXPLORE_GARDEN",
  },
};
