/**
 * Harvest Schema - Goal-based relationship nurturing algorithms
 * 
 * The Harvest module proactively suggests relationship maintenance
 * based on user-selected algorithms (goals) that align with their values.
 */

import { co, z } from "jazz-tools";

/**
 * Algorithm Types - Different approaches to relationship maintenance
 * 
 * Based on psychological frameworks and relationship research:
 * - Tend & Befriend: Focus on emotional support and deepening bonds (Taylor, 2006)
 * - Plant & Prune: Strategic allocation of social energy (Dunbar, 1998)
 * - Cultivate: Consistent maintenance and growth (Reis & Shaver, 1988)
 */
export type AlgorithmType = 
  | "TEND_AND_BEFRIEND"    // Nurture existing close relationships
  | "PLANT_AND_PRUNE"      // Strategic pruning + planting new connections
  | "CULTIVATE"            // Consistent maintenance across all layers
  | "INNER_CIRCLE"         // Focus intensely on intimate core
  | "EXPAND_HORIZONS"      // Meet new people, expand social circle
  | "REKINDLE"             // Reconnect with past relationships
  | "BALANCE";             // Maintain equilibrium across all layers

/**
 * Algorithm configurations with research-backed parameters
 */
export interface AlgorithmConfig {
  type: AlgorithmType;
  name: string;
  description: string;
  targetLayers: number[];        // Which Dunbar layers to focus on
  checkFrequency: number;        // Days between checks
  actionThreshold: number;       // Days since last contact before suggesting action
  priorityWeights: {             // How to prioritize suggestions
    recency: number;             // Weight for time since last contact
    frequency: number;           // Weight for usual contact frequency
    quality: number;             // Weight for interaction quality
    familyBonus: number;         // Extra weight for family
  };
}

/**
 * User's active algorithms
 * Users can have multiple algorithms running simultaneously
 */
export const HarvestAlgorithm = co.map({
  type: z.string(),
  enabled: z.boolean(),
  createdAt: z.string(),
  lastRunAt: z.string().optional(),
  customSettings: z.string().optional(), // JSON string of Partial<AlgorithmConfig>
});

/**
 * Suggested actions generated by algorithms
 */
export const HarvestSuggestion = co.map({
  contactId: z.string(),               // Reference to Contact
  algorithmType: z.string(),           // Which algorithm generated this
  actionType: z.string(),              // "CALL" | "TEXT" | "MEET" | "CHECK_IN"
  priority: z.number(),                // 0-100, higher = more urgent
  reason: z.string(),                  // Human-readable explanation
  generatedAt: z.string(),             // ISO timestamp
  dismissedAt: z.string().optional(),  // User can dismiss suggestions
  completedAt: z.string().optional(),  // Marked complete when action taken
  snoozedUntil: z.string().optional(), // Temporarily hide suggestion
});

/**
 * Notification schedule for push reminders
 */
export const HarvestNotificationSettings = co.map({
  enabled: z.boolean(),
  frequency: z.string(),                    // "DAILY" | "WEEKLY" | "BIWEEKLY"
  preferredTime: z.string(),                // "08:00" format
  preferredDays: z.array(z.string()),       // ["MON", "WED", "FRI"]
  quietHoursStart: z.string().optional(),   // "22:00"
  quietHoursEnd: z.string().optional(),     // "08:00"
});

/**
 * User's Harvest profile - all algorithm and notification settings
 */
export const HarvestProfile = co.map({
  lastGeneratedAt: z.string().optional(),   // When suggestions were last generated
  totalActionsCompleted: z.number(),        // Gamification metric
  currentStreak: z.number(),                // Days in a row with completed actions
  longestStreak: z.number(),                // Best streak ever
  notificationEnabled: z.boolean(),
  notificationFrequency: z.string(),
  notificationTime: z.string(),
});

// Store algorithms and suggestions as lists on the root
export const HarvestAlgorithmList = co.list(HarvestAlgorithm);
export const HarvestSuggestionList = co.list(HarvestSuggestion);

/**
 * Algorithm Presets - Pre-configured for different relationship goals
 */
export const ALGORITHM_PRESETS: Record<AlgorithmType, AlgorithmConfig> = {
  TEND_AND_BEFRIEND: {
    type: "TEND_AND_BEFRIEND",
    name: "Tend & Befriend",
    description: "Nurture your closest relationships with regular check-ins and emotional support. Focuses on layers 0-2.",
    targetLayers: [0, 1, 2],
    checkFrequency: 1, // Daily
    actionThreshold: 7, // Suggest if no contact in 7 days
    priorityWeights: {
      recency: 0.5,
      frequency: 0.2,
      quality: 0.2,
      familyBonus: 0.1,
    },
  },
  PLANT_AND_PRUNE: {
    type: "PLANT_AND_PRUNE",
    name: "Plant & Prune",
    description: "Strategic social energy allocation. Prune weak connections, invest in promising ones. Focuses on layers 2-4.",
    targetLayers: [2, 3, 4],
    checkFrequency: 7, // Weekly
    actionThreshold: 30, // Suggest if no contact in 30 days
    priorityWeights: {
      recency: 0.3,
      frequency: 0.4, // Prioritize people you usually talk to often
      quality: 0.2,
      familyBonus: 0.1,
    },
  },
  CULTIVATE: {
    type: "CULTIVATE",
    name: "Cultivate",
    description: "Consistent maintenance across all relationship layers. Balanced approach to keep your garden healthy.",
    targetLayers: [0, 1, 2, 3, 4],
    checkFrequency: 3, // Every 3 days
    actionThreshold: 14, // Suggest if no contact in 14 days
    priorityWeights: {
      recency: 0.3,
      frequency: 0.3,
      quality: 0.3,
      familyBonus: 0.1,
    },
  },
  INNER_CIRCLE: {
    type: "INNER_CIRCLE",
    name: "Inner Circle",
    description: "Intensely focus on your intimate core and sympathy group. Deep over wide.",
    targetLayers: [0, 1],
    checkFrequency: 1, // Daily
    actionThreshold: 3, // Very short threshold
    priorityWeights: {
      recency: 0.6, // Heavy weight on recency
      frequency: 0.1,
      quality: 0.2,
      familyBonus: 0.1,
    },
  },
  EXPAND_HORIZONS: {
    type: "EXPAND_HORIZONS",
    name: "Expand Horizons",
    description: "Focus on meeting new people and moving acquaintances to closer layers.",
    targetLayers: [3, 4, 5],
    checkFrequency: 7, // Weekly
    actionThreshold: 60, // Long threshold - focus on people you rarely see
    priorityWeights: {
      recency: 0.2,
      frequency: 0.2,
      quality: 0.4, // Prioritize quality interactions
      familyBonus: 0.2,
    },
  },
  REKINDLE: {
    type: "REKINDLE",
    name: "Rekindle",
    description: "Reconnect with people you've drifted from. Revive old friendships.",
    targetLayers: [2, 3, 4, 5],
    checkFrequency: 14, // Biweekly
    actionThreshold: 90, // Suggest people you haven't talked to in 3+ months
    priorityWeights: {
      recency: 0.7, // Heavy focus on people you haven't talked to
      frequency: 0.1,
      quality: 0.1,
      familyBonus: 0.1,
    },
  },
  BALANCE: {
    type: "BALANCE",
    name: "Balance",
    description: "Maintain equilibrium across all layers. No one gets neglected.",
    targetLayers: [0, 1, 2, 3, 4],
    checkFrequency: 5, // Every 5 days
    actionThreshold: 21, // 3 weeks
    priorityWeights: {
      recency: 0.25,
      frequency: 0.25,
      quality: 0.25,
      familyBonus: 0.25,
    },
  },
};

/**
 * Action type definitions
 */
export const ACTION_TYPES = {
  CALL: {
    name: "Call",
    icon: "📞",
    description: "Have a voice conversation",
    typicalDuration: 15, // minutes
  },
  TEXT: {
    name: "Text",
    icon: "💬",
    description: "Send a message",
    typicalDuration: 5,
  },
  MEET: {
    name: "Meet",
    icon: "🤝",
    description: "Meet in person",
    typicalDuration: 60,
  },
  CHECK_IN: {
    name: "Check In",
    icon: "👋",
    description: "Quick hello or status check",
    typicalDuration: 2,
  },
  VIDEO_CALL: {
    name: "Video Call",
    icon: "📹",
    description: "Video chat",
    typicalDuration: 30,
  },
} as const;
